### ISSUE TITLE
1.18.1please

### ISSUE THREAD

**Issue by blood789** [CraftTweaker/CraftTweaker#1413] opened 2021-12-25 05:24 UTC
### Describe the feature you'd like

Hello，When will update to 1.18.1?

### Minecraft version

Other

**Comment by jaredlll08** [comment] 2021-12-25 05:58
Basically a duplicate of https://github.com/CraftTweaker/CraftTweaker/issues/1368

We are busy working on the updates.

**Closed as completed by jaredlll08** 2021-12-25 05:58 UTC

**Comment by HonzaVinCZ** [comment] 2022-01-03 15:24
> Basically a duplicate of #1368
> 
> We are busy working on the updates.

Can you at least rougly estimate when could 1.18 update happen? CT was always definitely one of the best modpack making tools and there is still nothing like that in 1.18.

**Comment by jaredlll08** [comment] 2022-01-03 15:47
I wish I could give you an estimate, a lot has changed with how we are doing things that is unfortunately making the port take much longer than expected, I don't even have an estimate for myself.

**Comment by jaredlll08** [comment] 2022-01-10 01:31
The mod has been ported to both 1.17 and 1.18 on both Fabric and Forge.
