### ISSUE TITLE
java.lang.IllegalStateException: An error occurred while initializing plugins

### ISSUE THREAD

**Issue by HungryMuttis** [CraftTweaker/CraftTweaker#1784] opened 2024-12-01 09:37 UTC
### Issue description

When loading Minecraft Forge 1.20.1 with other mods (shown in the crash report) CraftTweaker fails to load.

### Steps to reproduce

Install all the mods show in the crash report.

### Script used

none

### The crafttweaker.log file

https://github.com/user-attachments/files/17968405/crafttweaker.log

### Minecraft version

1.20.1

### Modloader

Forge

### Modloader version

47.3.12

### CraftTweaker version

14.0.44

### Other relevant information

[crash-2024-12-01_11.24.15-fml.txt](https://github.com/user-attachments/files/17968399/crash-2024-12-01_11.24.15-fml.txt)

### The latest.log file

https://github.com/user-attachments/files/17968401/latest.log

**Comment by jaredlll08** [comment] 2024-12-01 09:48
CreateSifter requires CreateTweaker.
Duplicate of:
https://github.com/oierbravo/createsifter/issues/47
https://github.com/CraftTweaker/CraftTweaker/issues/1670
https://github.com/CraftTweaker/CraftTweaker/issues/1708
https://github.com/CraftTweaker/CraftTweaker/issues/1714
https://github.com/CraftTweaker/CraftTweaker/issues/1721
https://github.com/CraftTweaker/CraftTweaker/issues/1739

**Closed as not planned by jaredlll08** 2024-12-01 09:48 UTC

**Comment by HungryMuttis** [comment] 2024-12-01 09:50
Thank you!
