### ISSUE TITLE
Loot tables are broken with Porting Lib installed

### ISSUE THREAD

**Issue by BluSpring** [CraftTweaker/CraftTweaker#1702] opened 2024-01-21 04:56 UTC
### Issue description

With the current version of Porting Lib installed, every single loot table stops functioning. This includes:
- Chest loot
- Mob drops
- Fishing

### Steps to reproduce

- Install Porting Lib
- Kill a mob with a Looting 3 sword OR open a chest in a generated structure

### Script used

none

### The crafttweaker.log file

https://pastebin.com/iasBY1NA

### Minecraft version

1.20.1

### Modloader

Fabric

### Modloader version

0.15.6

### CraftTweaker version

1.20.1-14.0.30

### Other relevant information

Fabric API: 0.91.0+1.20.1
[Porting Lib: 2.1.1178+1.20.1](https://mvn.devos.one/#/snapshots/io/github/fabricators_of_create/Porting-Lib/Porting-Lib/2.1.1178+1.20.1)

### The latest.log file

https://pastebin.com/nWRGuGp3

**Comment by Witixin1512** [comment] 2024-02-23 19:15
Can you check whether the newer version of Porting Lib does indeed fix this?

**Comment by jaredlll08** [comment] 2024-04-23 03:43
PortingLib says that the [root cause has been fixed[(https://github.com/Fabricators-of-Create/Porting-Lib/issues/77#issuecomment-1949131246), so I'm going to close this.

**Closed as not planned by jaredlll08** 2024-04-23 03:43 UTC
Labels: Needs Info
