### ISSUE TITLE
ScriptProviderCustom could not work normally

### ISSUE THREAD

**Issue by Ecdcaeb** [CraftTweaker/CraftTweaker#1720] opened 2024-03-17 04:47 UTC
### Issue description

ScriptProviderCustom could not work normally.

To new a `ScriptProviderCustom`, we provide a moduleName, which is the `IScriptIterator`'s groupName and the ClassName.

Only [ScriptIteratorSingle](https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/runtime/providers/ScriptIteratorSingle.java) could work normally. Other iterator, has more than one scripts but same group name, will lead the class generated from scripts has same class name.

>two scripts, with same name, were loaded. The later one,  what i show to you, was not loaded into ClassLoader since there was a exist class. So, the Item register was invoked when recipe event.

I have tested it again and again. It could not `add(String name, byte[] content)` more than one. The first will overwrite the all laters.

I have rewrited a new `ScriptProviderCustom`, [here](https://github.com/Ecdcaeb/ResourceModLoader/blob/main/src/main/java/mods/Hileb/rml/compat/crt/RMLScriptProvider.java), to solve it.

### Script used

*

### The crafttweaker.log file

https://mclo.gs/dc73zbL

### Minecraft version

1.12

### Modloader

All

### Modloader version

*

### CraftTweaker version

*

### The latest.log file

*

**Comment by TheSilkMiner** [comment] 2024-03-17 08:50
Why is this an issue? `ScriptProviderCustom` allows you to provide a set of scripts that are logically grouped into the same module.

Logically speaking, two scripts with the same name in the same module cannot coexist: try to put two classes in Java with the same exact fully qualified name in two different JARs and load them both as part of the unnamed module. You'll notice the class that gets loaded is now determined by a coin toss.

If only, I'd recognize this issue as an error where attempting to redefine a script should throw as something very wrong has happened, instead of silently ignoring the request.

**Comment by Ecdcaeb** [comment] 2024-03-17 14:24
> Why is this an issue? allows you to provide a set of scripts that are logically grouped into the same module.`ScriptProviderCustom`
> 
> Logically speaking, two scripts with the same name in the same module cannot coexist: try to put two classes in Java with the same exact fully qualified name in two different JARs and load them both as part of the unnamed module. You'll notice the class that gets loaded is now determined by a coin toss.
> 
> If only, I'd recognize this issue as an error where attempting to redefine a script should throw as something very wrong has happened, instead of silently ignoring the request.

no, all scripts in one `ScriptProviderCustom` will have the same group name and the same class name. Just like same file name i means.

**Comment by jaredlll08** [comment] 2024-04-23 02:30
I am still not sure what the issue is here, but seeing as it is 1.12, and you have a working fix, I am going to be closing this.

**Closed as not planned by jaredlll08** 2024-04-23 02:30 UTC
