### ISSUE TITLE
Cannot cast IItemStack[] to IIngredient[]

### ISSUE THREAD

**Issue by friendlyhj** [CraftTweaker/CraftTweaker#1323] opened 2021-07-19 09:38 UTC
### Issue description

I tried adding a rune altar recipe. All inputs are `IItemStack`s. Then it introduced an error: `Cannot cast IItemStack[] to IIngredient[]`. If I cast one of input to `IIngredient`, it works well. However, `IItemStack extends IIngredient`, the error is unreasonable.

### Steps to reproduce

* Install Botania 1.16.5-416 and Mythic Botany
* Run the script below
* Get error

### Script used

https://gist.github.com/friendlyhj/61a105c88602914791ac7a4ba6aa34de

### The crafttweaker.log file

https://gist.github.com/friendlyhj/61a105c88602914791ac7a4ba6aa34de

### Minecraft version

1.16

### Forge version

36.1.0

### CraftTweaker version

7.1.0.355

### The latest.log file

No need to give, I think.

**Comment by jaredlll08** [comment] 2021-09-19 23:34
So I cloned botania (So using https://github.com/VazkiiMods/Botania/commit/f7f6c00dd1637ab75ae35db8e2671d9ec81c6b1e) and I'm unable to reproduce, it seems to be working as intended.

You are using Botania `1.16.5-416` and I believe they made some changes in newer versions, could you try a new version and see if it worked?

Also this is the script I tested with
```zenscript
import mods.botania.RuneAltar;

<recipetype:botania:runic_altar>.addRecipe("aura_ring_greatest",
	<item:minecraft:dirt>,
	5000000,
	<item:botania:aura_ring_greater>,
	<item:minecraft:diamond>,
	<item:botania:rune_mana>,
	<item:botania:rune_mana>,
	<item:botania:life_essence>,
	<item:botania:life_essence>,
	<item:botania:life_essence>,
	<item:botania:life_essence>);
```

**Comment by friendlyhj** [comment] 2021-09-20 02:08
Well, I updated botania and crafttweaker.
```zenscript
<recipetype:botania:runic_altar>.addRecipe("aura_ring_greatest", 
	<item:mythicbotany:aura_ring_greatest>, 
	5000000, 
	<item:botania:aura_ring_greater>, 
	<item:mythicbotany:alfsteel_ingot>, 
	<item:botania:rune_mana>, 
	<item:botania:rune_mana>, 
	<item:botania:life_essence>, 
	<item:botania:life_essence>, 
	<item:botania:life_essence>, 
	<item:botania:life_essence>);
```
Using varargs, it worked. But if I used array...
```zenscript
<recipetype:botania:runic_altar>.addRecipe("aura_ring_greatest", 
	<item:mythicbotany:aura_ring_greatest>, 
	5000000, 
	[<item:botania:aura_ring_greater>, 
	<item:mythicbotany:alfsteel_ingot>, 
	<item:botania:rune_mana>, 
	<item:botania:rune_mana>, 
	<item:botania:life_essence>, 
	<item:botania:life_essence>, 
	<item:botania:life_essence>, 
	<item:botania:life_essence>]);
```
It wouldn't work. It still complained error shown in the title.

**Comment by jaredlll08** [comment] 2021-09-20 21:29
This should be fixed by https://github.com/ZenCodeLang/ZenCode/pull/48

**Comment by jaredlll08** [comment] 2022-01-10 01:34
I believe this was fixed by https://github.com/ZenCodeLang/ZenCode/pull/71

**Closed as completed by jaredlll08** 2022-01-10 01:34 UTC
