### ISSUE TITLE
Recipe not giving multiple outputs

### ISSUE THREAD

**Issue by AlexGuignard** [CraftTweaker/CraftTweaker#1555] opened 2022-09-16 10:02 UTC
### Issue description

I have tried to insert a custom craft to resolve a conflict between two mods , the recipe is as follows :

val iron = \<minecraft:iron_ingot\>;
val iron_f = \<advgenerators:iron_frame\>;
recipes.addShaped("Iron_frame", iron_f * 2,[
[iron,null,iron],
[null,null,null],
[iron,null,iron]
]);

![image](https://user-images.githubusercontent.com/72733620/190613206-64040049-a49a-4bb0-99ed-2831aabeabcc.png)
Craft looks good in JEI 

but when crafted only gives one :
![image](https://user-images.githubusercontent.com/72733620/190613287-c5326fea-064c-4872-a127-2288b574e0d3.png)
( same in normal crafting table )

### Steps to reproduce

Script is in the report.

### Script used

https://pastebin.com/aPkZkdGF

### The crafttweaker.log file

https://pastebin.com/xuqQRtUg

### Minecraft version

1.12

### Modloader

Forge

### Modloader version

14.23.5.2860

### CraftTweaker version

4.1.20.680

### Other relevant information

modlist :  
AbyssalCraft-1.12.2-1.10.4.jar
 ActuallyAdditions-1.12.2-r152.jar
 ae2stuff-0.7.0.4-mc1.12.2.jar
 AE2WTLib-1.12.2-1.0.34.jar
 aether_ii-1.12.2-0.3.0+build411-universal.jar
 aiotbotania-0.7.1.jar
 AkashicTome-1.2-12.jar
 AppleCore-mc1.12.2-3.4.0.jar
 appliedenergistics2-rv6-stable-7.jar
 Aroma1997Core-1.12.2-2.0.0.2.jar
 Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar
 AromaBackup-1.12.2-2.1.1.4.jar
 astralsorcery-1.12.2-1.10.27.jar
 AutoRegLib-1.3-32.jar
 Baubles-1.12-1.5.2.jar
 baubley-heart-canisters-1.12.2-2.0.3.jar
 bdlib-1.14.3.12-mc1.12.2.jar
 BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
 BetterFps-1.4.8.jar
 BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
 BloodMagic-1.12.2-2.4.3-105.jar
 bonsaitrees-1.1.4-b170.jar
 Bookshelf-1.12.2-2.3.590.jar
'Botania r1.10-364.4.jar'
 BotanicAdditions-1.12.2-12.2.6.jar
 BuildingGadgets-2.8.4.jar
 Chameleon-1.12-4.1.3.jar
 chickens-6.0.4.jar
 Chisel-MC1.12.2-1.0.2.45.jar
 chiselsandbits-14.33.jar
 CodeChickenLib-1.12.2-3.2.3.358-universal.jar
 CoFHCore-1.12.2-4.6.6.1-universal.jar
 CoFHWorld-1.12.2-1.4.0.1-universal.jar
 comforts-1.12.2-1.4.1.3.jar
 CommonCapabilities-1.12.2-2.4.8.jar
 compactmachines3-1.12.2-3.0.18-b278.jar
 Controlling-3.0.10.jar
 CookingForBlockheads_1.12.2-6.5.0.jar
 CosmeticArmorReworked-1.12.2-v5a.jar
 CraftTweaker2-1.12-4.1.20.680.jar
 CTM-MC1.12.2-1.0.2.31.jar
 Cucumber-1.12.2-1.1.3.jar
 Cyclic-1.12.2-1.20.12.jar
 CyclopsCore-1.12.2-1.6.7.jar
 DarkUtils-1.12.2-1.8.230.jar
 enchantingwiththaumcraft-1.4.jar
 EnchantmentDescriptions-1.12.2-1.1.15.jar
 EnderCore-1.12.2-0.5.76.jar
 EnderIO-base-1.12.2-5.3.70.jar
 EnderIO-conduits-1.12.2-5.3.70.jar
 EnderIO-conduits-appliedenergistics-1.12.2-5.3.70.jar
 EnderIO-integration-forestry-1.12.2-5.3.70.jar
 EnderIO-integration-tic-1.12.2-5.3.70.jar
 EnderIO-machines-1.12.2-5.3.70.jar
 EnderStorage-1.12.2-2.4.6.137-universal.jar
 enhancedarmaments-1.3.21.jar
 environmentalmaterials-1.12.2-1.0.20.1.jar
 environmentaltech-1.12.2-2.0.20.1.jar
 Erebus-1.0.32.jar
 erebusfix-1.12.2-0.0.0.1.jar
 etlunar-1.12.2-2.0.20.1.jar
 ExtraCells-1.12.2-2.6.7.jar
 extrautils2-1.12-1.9.9.jar
 ExtremeReactors-1.12.2-0.4.5.68.jar
 FastLeafDecay-v14.jar
 findme-1.12.2-1.1.0-8.jar
 FluxNetworks-1.12.2-4.1.1.34.jar
 foamfix-0.10.14-1.12.2.jar
 forestry_1.12.2-5.8.2.387.jar
 Forgelin-1.8.4.jar
 ForgeMultipart-1.12.2-2.6.2.83-universal.jar
 framedcompactdrawers-1.2.7.jar
 FTBBackups-1.1.0.1.jar
 FTBLib-5.4.7.2.jar
 FTBUtilities-5.4.1.131.jar
 furniture-6.3.2-1.12.2.jar
 generators-0.9.20.12-mc1.12.2.jar
 gravestone-1.10.3.jar
 Guide-API-1.12-2.1.8-63.jar
 HammerLib-1.12.2-2.0.6.32.jar
 Hwyla-1.8.26-B41_1.12.2.jar
 ImmersiveEngineering-0.12-98.jar
 immersivepetroleum-1.12.2-1.1.10.jar
 industrialcraft-2-2.8.170-ex112.jar
 industrialforegoing-1.12.2-1.12.13-237.jar
 IntegratedCrafting-1.12.2-1.0.10.jar
 IntegratedDynamics-1.12.2-1.1.11.jar
 IntegratedTerminals-1.12.2-1.0.14.jar
 IntegratedTunnels-1.12.2-1.6.14.jar
 InventoryTweaks-1.63.jar
 ironchest-1.12.2-7.0.72.847.jar
 jei_1.12.2-4.16.1.301.jar
 journeymap-1.12.2-5.7.1.jar
 JustEnoughResources-1.12.2-0.9.2.60.jar
 KubeJS-forge-1.12.2-1.1.0.65.jar
 lootr-1.12.2-0.4.4.jar
 LunatriusCore-1.12.2-1.2.0.42-universal.jar
 Mantle-1.12-1.3.3.55.jar
 mcjtylib-1.12-3.5.4.jar
 Mekanism-1.12.2-9.8.3.390.jar
 MekanismGenerators-1.12.2-9.8.3.390.jar
 MekanismTools-1.12.2-9.8.3.390.jar
 mixinbooter-5.0.jar
 moartinkers-0.6.0.jar
 MobGrindingUtils-0.3.13.jar
 modular-routers-1.12.2-3.3.0-33.jar
 morechickens-1.12.2-3.1.0.jar
 Morpheus-1.12.2-3.5.106.jar
 MouseTweaks-2.10-mc1.12.2.jar
 MysticalAgradditions-1.12.2-1.3.2.jar
 MysticalAgriculture-1.12.2-1.7.5.jar
 NaturesCompass-1.12.2-1.8.5.jar
 NotEnoughIDs-1.5.4.4.jar
 NuclearCraft-2.18zzz-1.12.2.jar
 OpenBlocks-1.12.2-1.8.1.jar
 OpenModsLib-1.12.2-0.12.2.jar
 OreExcavation-1.4.150.jar
 p455w0rdslib-1.12.2-2.3.161.jar
 pamscookables-1.1.jar
 Pam's Get all the Seeds 1.12a.jar
 Pam's HarvestCraft 1.12.2zg.jar
 phosphor-1.12.2-0.2.6+build50-universal.jar
 Placebo-1.12.2-1.6.0.jar
 Quark-r1.6-179.jar
 RedstoneFlux-1.12-2.1.1.1-universal.jar
 Reliquary-1.12.2-1.3.4.796.jar
 rftools-1.12-7.73.jar
 rftoolsdim-1.12-5.71.jar
 rftoolspower-1.12-1.2.0.jar
 roost-1.12.2-2.0.10.jar
 rustic-1.1.7.jar
 rusticbopwoods-1.0.jar
 Rustic Thaumaturgy-4.4a.jar
 Schematica-1.12.2-1.8.0.169-universal.jar
 solcarrot-1.12.2-1.8.4.jar
 StorageDrawers-1.12.2-5.4.2.jar
 supermartijn642corelib-1.0.19-forge-mc1.12.jar
 tc6aspects4jei-0.0.2a.jar
 TConstruct-1.12.2-2.13.0.183.jar
 tesla-core-lib-1.12.2-1.0.18.jar
 tetra-1.12.2-0.39.1.jar
 Thaumcraft-1.12.2-6.1.BETA26.jar
 ThaumicAdditions-1.12.2-12.7.8.jar
 ThaumicAugmentation-1.12.2-2.1.7.jar
 ThaumicInventoryScanning_1.12.2-2.0.10.jar
 thaumictinkerer-1.12.2-5.0-620a0c5.jar
 thaumicwonders-1.8.2.jar
 ThermalCultivation-1.12.2-0.3.6.1-universal.jar
 ThermalDynamics-1.12.2-2.5.6.1-universal.jar
 ThermalExpansion-1.12.2-5.5.7.1-universal.jar
 ThermalFoundation-1.12.2-2.6.7.1-universal.jar
 ThermalInnovation-1.12.2-0.3.6.1-universal.jar
 thermallogistics-0.3-43.jar
 ThermalTinkering-1.12.2-2.0.1.jar
 tinkersjei-1.2.jar
 torchmaster_1.12.2-1.8.5.0.jar
 Translocators-1.12.2-2.5.2.81-universal.jar
 trashcans-1.0.15-forge-mc1.12.jar
 valkyrielib-1.12.2-2.0.20.1.jar
 Waystones_1.12.2-4.1.0.jar
 WirelessCraftingTerminal-1.12.2-3.12.97.jar
 WirelessFluidTerminal-1.12.2-1.0.4.jar
 WirelessInterfaceTerminal-1.12.2-1.0.2.jar
 WirelessPatternTerminal-1.12.2-1.0.3.jar
 woot-1.12.2-1.4.11.jar
 xnet-1.12-1.8.2.jar
 zerocore-1.12.2-0.1.2.9.jar

### The latest.log file

https://pastebin.com/P3vrvdtF

**Comment by AlexGuignard** [comment] 2022-09-16 10:52
The problem is only present on server scripts are the same both sides

**Comment by kindlich** [comment] 2022-09-16 16:57
First, recipe names should not contain uppercased letters (not sure if that's relevant in your case, though).
Second, is this only visual or does the recipe actually return a single item?
Like when you craft the recipe, put the output into your inventory, logout and then login again, do you have one item or two in your inventory?

Also, asking just in case, are you _absolutely_ sure the recipes on the client and on the server are the same?

**Comment by jaredlll08** [comment] 2022-09-16 17:43
try crafting the item in the vanilla crafting table

**Comment by AlexGuignard** [comment] 2022-09-25 20:34
> First, recipe names should not contain uppercased letters (not sure if that's relevant in your case, though). Second, is this only visual or does the recipe actually return a single item? Like when you craft the recipe, put the output into your inventory, logout and then login again, do you have one item or two in your inventory?
> 
> Also, asking just in case, are you _absolutely_ sure the recipes on the client and on the server are the same?



> try crafting the item in the vanilla crafting table

""( same in normal crafting table )""

The craft only game 1 item visually and factually
The server finally after 5 total restarts finally gave the right ammount 
The scripts were done on the server and sent to clients afterwards so yes the scripts were and are the same

**Comment by jaredlll08** [comment] 2022-09-26 00:01
Can you try with just CraftTweaker, JEI and Advance Generators please

**Comment by AlexGuignard** [comment] 2022-09-26 09:56
![image](https://user-images.githubusercontent.com/72733620/192247980-bc4c5a31-f720-46b0-9e72-8dbce80313f0.png)
![image](https://user-images.githubusercontent.com/72733620/192248053-a8796401-dd40-4cd3-81d5-7dd5f8368ce1.png)
Doesnt fuck up anymore
dunno what was doing the deed wrong but eh :/ dunno
![image](https://user-images.githubusercontent.com/72733620/192248168-d688cf80-f29a-4604-bfce-dd77c2189bf6.png)

**Comment by jaredlll08** [comment] 2022-09-26 12:29
Can you try adding the mods back one by one to see what caused it

**Comment by BitBlitObviMormon** [comment] 2022-12-16 21:41
I got the same issue with createtweaker and tinker's construct, however after restarting the game I could not reproduce the issue. This bug seems to just "turn on" seemingly randomly. When that happens it'll display the proper output in the recipe but then only give one output when crafting. Resetting the game fixes the issue.

**Comment by jaredlll08** [comment] 2022-12-16 21:58
Your issue is most likely a different issue seeing as the original one was 1.12 and createtweaker isn't on 1.12.

I still highly doubt it is CraftTweaker that is causing it, it must be another mod or else we would have a lot more reports.

**Comment by AlexGuignard** [comment] 2022-12-17 02:32
Yeah no defintly no 1.12.2 version
![image](https://user-images.githubusercontent.com/72733620/208219566-ad60e6bf-5fc2-4998-8bce-d5158512b152.png)

**Comment by jaredlll08** [comment] 2022-12-17 03:07
> Yeah no defintly no 1.12.2 version ![image](https://user-images.githubusercontent.com/72733620/208219566-ad60e6bf-5fc2-4998-8bce-d5158512b152.png)

***Craft***Tweaker is on 1.12 yes, but ***Create**T*weaker for the ***Create*** mod is not on 1.12 as Create never existed on that version.
<https://www.curseforge.com/minecraft/mc-mods/createtweaker>

**Comment by BitBlitObviMormon** [comment] 2022-12-17 06:23
Yes, I got this issue on 1.18.2, not 1.12.

**Comment by jaredlll08** [comment] 2023-11-21 12:19
I'm going to close this issue as it is 100% another mod messing up, and the only way to figure out which mod is to binary search the mods, figure out which mod causes it and report it to them.

If other people are experiencing the same issue, then please make a new issue with updated information.

**Closed as not planned by jaredlll08** 2023-11-21 12:19 UTC
