### ISSUE TITLE
Botania mana infusion not working

### ISSUE THREAD

**Issue by Nagasena12** [CraftTweaker/CraftTweaker#1623] opened 2023-02-24 15:23 UTC
### Issue description

I am trying to edit a mana infusion recipe using crafttweaker but it seems not to work

### Script used

https://gist.github.com/Nagasena12/27aa31d5ef781c7af5c661cbb066a01c

### The crafttweaker.log file

https://gist.github.com/Nagasena12/fe0f750ef08b1c2ece74a96a20aa09de

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.2.1

### CraftTweaker version

9.1.205

### The latest.log file

https://gist.github.com/Nagasena12/c1495c7971906bb7caa36219fda402d4

**Comment by jaredlll08** [comment] 2023-11-21 12:15
The issue is that you are trying to call `remove` as if it was a static method, you should be doing:
```
<recipetype:botania:mana_infusion>.remove(<item:botania:manasteel_ingot>);

<recipetype:botania:mana_infusion>.addRecipe("bettermanasteel", <item:botania:manasteel_ingot>, <item:create:iron_sheet>, 3000);
```

I understand the docs say otherwise, it will be fixed in an upcoming doc rework.

**Closed as completed by jaredlll08** 2023-11-21 12:15 UTC
