### ISSUE TITLE
Craft Tweaker vs Tinkers Construct

### ISSUE THREAD

**Issue by MattB70** [CraftTweaker/CraftTweaker#1595] opened 2022-11-25 23:30 UTC
### Issue description

This crash repeats every few hours. After the first few crashes I removed all Craft Tweaker scripts from the server to see if it continues, and it does.

### Steps to reproduce

Run Craft Tweaker and Tinkers Construct at the same time, perhaps needing a Tinkers Construct faucet present and ticking. Aside from that, unknown. I'd like to give more info, but I don't have much more. Sorry.

### Script used

NA, removed all after the first few occurances of the crash.

### The crafttweaker.log file

https://gist.github.com/MattB70/da24175df22c4579fa4320ac3c00815d

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.84

### CraftTweaker version

9.1.197

### Other relevant information

Crash log: https://gist.github.com/MattB70/abdbbd40c2b46d5599043dcab1742aba

### The latest.log file

https://gist.github.com/MattB70/779186fe96c0d197f1931950c06c4fd3

**Comment by jaredlll08** [comment] 2022-11-27 21:37
Just to confirm, are there ANY files in the `scripts` folder when you get that crafttweaker.log file?

**Comment by MattB70** [comment] 2022-11-27 21:50
Nothing, no folders, files, or hidden files. The world was created with two scripts that altered crafting recipes, though none with Tinkers, and none that altered tags. Now without any scripts it continues to crash.

The first crash will always be the one posted above, and then a few hours later it will crash again, but will only report running out of heap space. It seems consistent.

For the time being I've ported all my Craft Tweaker changes to a mod and will be running that, so this isn't a big deal unless another person reports it.

**Comment by jaredlll08** [comment] 2022-11-28 14:40
According to the log file, there is a file called `.zs` in the folder and it is being read:
https://gist.github.com/MattB70/da24175df22c4579fa4320ac3c00815d#file-crafttweaker-log-L21

There is a bug that means that you can't use a file just called `.zs`, it would need to have a name, that bug is causing script compilation to fail.

The actual crash is caused by an oversight in our code which I can fix, but it won't fix `.zs` file.

**Closed as completed** 2022-11-28 14:56 UTC
