### ISSUE TITLE
Crafftweaker Server need /reload every time you log in.

### ISSUE THREAD

**Issue by Alfog** [CraftTweaker/CraftTweaker#1441] opened 2022-02-03 05:58 UTC
### Issue description

My crafttweaker scrips used for custom recipes will work perfectly fine in SP but the moment i use them on a server they either don't work at all or they need to be reloaded by /reload command. The client side scripts and server side are the exact same.

### Steps to reproduce

_Start a MP Server World and Log in_

### Script used

https://pastebin.com/m7GeqQNs https://pastebin.com/4xSh3TU8 https://pastebin.com/48LK1jJL

### The crafttweaker.log file

https://pastebin.com/jQSuzYUz

### Minecraft version

1.16

### Modloader

Forge

### Modloader version

36.2.22

### CraftTweaker version

1.16.5-7.1.2.489

### The latest.log file

https://pastebin.com/9ZY4R3VT

**Comment by jaredlll08** [comment] 2022-02-03 08:48
Please can we get the crafttweaker.log file from the server

**Comment by Alfog** [comment] 2022-02-03 12:09
Pro accounts are sold out and the log is to big, so i divided it up:
https://pastebin.com/xDvBvPpV part 1
https://pastebin.com/dyhmRXnv part 2
https://pastebin.com/d5cNkU96 part 3
https://pastebin.com/CdWdUNwa part 4

Im very sorry if this is a jumbled mess

**Comment by jaredlll08** [comment] 2022-02-03 12:15
can you upload it to https://gist.github.com/ instead then please, just easier to have them all in the same file

**Comment by Alfog** [comment] 2022-02-03 12:27
https://gist.github.com/Alfog/f3a669ccf921fe9373fe3b802d52c660#file-crafttweaker-server-log
I  hope i did it right

**Comment by jaredlll08** [comment] 2022-02-03 12:30
Just to confirm, all of the scripts have issues on a server right?
like none of them work at first (itemstages, recipe stages and normal crafting recipes)

Is this a normal "vanilla" forge server?

Can I also get the server latest.log file please

**Comment by Alfog** [comment] 2022-02-03 12:37
It is a custom modpack server, and yes the problem is on the server. If i load up singleplayer all the scripts work fine but on the server they dont work when i first log in, but if i run the command /reload it loads the scripts and works, but i have to do this for every time i log in, and every person individually.

https://gist.github.com/Alfog/f4d0d74fec5ccb1eaaad74b08d0c819b#file-server-latest-log

**Comment by jaredlll08** [comment] 2022-02-03 12:39
I was more asking if the server itself is Forge, or if it was something like mohist / spongeforge or something along those lines

**Comment by Alfog** [comment] 2022-02-03 12:41
ohh yes its a forge server, Forge 36.2.22

**Comment by jaredlll08** [comment] 2022-02-03 12:49
can you try downgrading to `1.16.5-7.1.2.488` and see if you still experience it?

**Comment by Alfog** [comment] 2022-02-03 13:03
yes it still does it after testing

**Comment by jaredlll08** [comment] 2022-02-03 13:03
can I get a modlist then please

**Comment by jaredlll08** [comment] 2022-02-03 13:06
Also I messed up, can you actually test on `1.16.5-7.1.2.487`, I made a change in `488` that I think may be causing this

**Comment by Alfog** [comment] 2022-02-03 13:08
okay will do, and here is the modlist
https://pastebin.com/z7UaUSgh

**Comment by Alfog** [comment] 2022-02-03 13:15
and yes still same issue

**Comment by jaredlll08** [comment] 2022-02-03 13:21
can I get a new crafttweaker.log file please (from the client), the one you provided doesn't appear to be one where you joined the server

**Comment by Alfog** [comment] 2022-02-03 13:21
should i delete it, then relog on the server to gen a fresh one?

**Comment by jaredlll08** [comment] 2022-02-03 13:22
Yes please

**Comment by Alfog** [comment] 2022-02-03 13:29
Okay i logged on the server but did not do anything while on the server, here is the log
https://pastebin.com/QYfYKC2Z

could it be these type of lines?:
[05:26:35.996][DONE][CLIENT][WARNING] Tag <tag:items:forge:ingots/compressed_iron> does not exist, replacing with empty IItemStack
[05:26:35.996][DONE][CLIENT][WARNING] Tag <tag:items:forge:dusts/certus_quartz> does not exist, replacing with empty IItemStack

**Comment by jaredlll08** [comment] 2022-02-03 13:31
Okay, so the scripts are being loaded on the client side, are you not seeing their effects ingame?

**Comment by Alfog** [comment] 2022-02-03 13:32
Not when i initially log in, only after i run the command /reload on the server do they work properly, but trying to run /reload with multiple people on tends to kick us all with a NullPointerException error

and if i leave the server and log back in, i need to /reload again

**Comment by jaredlll08** [comment] 2022-02-03 13:33
How are you checking if they work?

**Comment by Alfog** [comment] 2022-02-03 13:35
Through JEI, Part of the script are to hide items in JEI, when i log in i have the full 207 pages of JEI and when i reload it cuts it down to the amount of pages it should be at, and same with the custom recipes in JEI, before the reload the recipes are the "vanilla" recipes and after i reload they are my custom ones.

**Comment by jaredlll08** [comment] 2022-02-03 13:36
Okay, but can you craft the recipes that you are adding?

Like can you actually craft this recipe in a crafting table **without** doing a /reload?
```zenscript
 
craftingTable.addShaped("mecharm1", <item:create:mechanical_arm>, [
    [<item:create:brass_sheet>, <item:create:brass_sheet>, <item:immersiveengineering:ingot_steel>],
    [<item:create:brass_sheet>, <item:create:brass_casing>, <item:minecraft:air>], 
    [<item:create:brass_casing>, <item:create:precision_mechanism>, <item:create:brass_casing>]]);
```

**Comment by Alfog** [comment] 2022-02-03 13:41
Yes i can, so it is just visually not working client side?

**Comment by jaredlll08** [comment] 2022-02-03 13:42
It appears so, and that massively narrows down the issue.

**Comment by Alfog** [comment] 2022-02-03 13:42
That's the best news yet haha

**Comment by Alfog** [comment] 2022-02-03 13:48
Something i just noticed, when I log in the specific recipes I removed seem to be working now without a /reload( like the mechanical arm you had me try, the original recipe use to show and now it doesnt), it seems to be just JEI having troubles hiding items and the 'vanila' recipes i wanted gated behind stages.
If this helps

**Comment by jaredlll08** [comment] 2022-02-03 13:59
can you get me a new client latest.log file please, with you going into the server

**Comment by Alfog** [comment] 2022-02-03 14:12
https://gist.github.com/Alfog/9c08ab541bd7b6b68566b0b7eee7fe52#file-client-latest-log

**Comment by jaredlll08** [comment] 2022-02-03 14:27
Okay, so your pack has a lot of broken recipes that are unrelated to CraftTweaker, like:

```
[06:10:17] [main/ERROR]: Found a broken recipe: Theurgy theurgy:essentia/cobalt_ingot class com.github.klikli_dev.theurgy.common.crafting.recipe.EssentiaRecipe
Outputs:
net.minecraft.item.ItemStack: [[-56 air minecraft:air], [-56 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: [[1 cobalt_ingot tconstruct:cobalt_ingot]]
```
and some that are caused by your scripts:
```
[06:10:17] [main/ERROR]: Found a broken recipe: CraftTweaker crafttweaker:bitumen1 class blusunrize.immersiveengineering.api.crafting.BlastFurnaceRecipe
Outputs:
net.minecraft.item.ItemStack: [[1 bitumen immersivepetroleum:bitumen], [1 air minecraft:air nbt:{spell:{}}]]
Inputs:
net.minecraft.item.ItemStack: [[1 andesite_alloy create:andesite_alloy]]
```
That is why the initial JEI load fails.

You need to fix your scripts, and report the other issues to the other mod devs.

There is also a lot of:
```
[06:10:10] [main/ERROR]: Recipe has no output. Recipe Stages recipestages:spartanweaponry_bolt_tipped class com.blamejared.recipestages.recipes.RecipeStage
Outputs:
net.minecraft.item.ItemStack: [[1 air minecraft:air nbt:{spell:{}}]]
Inputs:
net.minecraft.item.ItemStack: []
```
My guess is that you are staging "special" recipes, that can't be staged and you will need to do them manually / not at all.

Either way, this is either other mods causing the issues, or a scripting issue, not much I can do on my side, so I'm going to close this issue.

**Closed as completed by jaredlll08** 2022-02-03 14:27 UTC

**Comment by Alfog** [comment] 2022-02-03 14:29
Thank you for you time on this issue, much appreciated
