### ISSUE TITLE
Log shows changes batched, recipes unchanged

### ISSUE THREAD

**Issue by blagdorfinguy** [CraftTweaker/CraftTweaker#1487] opened 2022-05-13 00:51 UTC
### Issue description

Two scripts are being loaded, and the log states that the changes are being compiled, batched, and executed successfully, but recipes remain unchanged.

### Steps to reproduce

Mods whose recipes to change are Waystones and Cyclic

### Script used

https://gist.github.com/blagdorfinguy/5e9f31378ec0ec82d5cf9bed606d6fb4 , https://gist.github.com/blagdorfinguy/98b0d3e060f1efd54acdcc4fbe0202fb

### The crafttweaker.log file

https://gist.github.com/blagdorfinguy/6009a03720ee89786bdc9c81ba3d9729

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.0.45

### CraftTweaker version

9.1.95

### The latest.log file

https://gist.github.com/blagdorfinguy/098c3e1546e787e0f2a93385ee256b21

**Comment by jaredlll08** [comment] 2022-05-13 16:28
Try updating CraftTweaker to https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/3787271

I'm not able to reproduce, using just:
WayStones
Balm
CraftTweaker
JEI

with:
```zenscript
import crafttweaker.api.recipe.Replacer;
Replacer.forMods("waystones").replace(<item:minecraft:purple_dye>, <item:minecraft:crying_obsidian>).replace(<item:minecraft:emerald>, <item:minecraft:emerald_block>).replace(<item:minecraft:obsidian>, <item:minecraft:respawn_anchor>).execute();
```
![image](https://user-images.githubusercontent.com/5553605/168326970-7578ac18-f2f4-4244-9249-1dbc3bfd531f.png)

**Comment by kindlich** [comment] 2022-06-24 14:57
@blagdorfinguy Since no answer came, I'm gonna close this for now.
If this is still an issue please reply here and we'll reopen.

**Closed as not planned by kindlich** 2022-06-24 14:57 UTC
Labels: Needs Info, Cannot Reproduce
