### ISSUE TITLE
Craft Tweaker fails to load correctly on server only

### ISSUE THREAD

**Issue by RamenG0D** [CraftTweaker/CraftTweaker#1753] opened 2024-07-06 09:57 UTC
### Issue description

I have tested this out to ensure the provided scripts can and do function in single player, which they do, but somehow they don't seem to work when on this server, the scripts do not function no recipe changes occur, and I'm unable to determine the cause through the logs.

if i can help, or more information is needed, just let me know!

### Steps to reproduce

launch on Minecraft server, then join, no recipes change...

### Script used

https://gist.github.com/RamenG0D/575b1a4b0e6f7bc8b34545810093937d

### The crafttweaker.log file

https://gist.github.com/RamenG0D/b5004c43b9be85bda1257bd7215e01fe

### Minecraft version

1.20.1

### Modloader

Fabric

### Modloader version

0.15.11

### CraftTweaker version

14.0.40

### Other relevant information

I have seen just one other [similar](https://github.com/CraftTweaker/CraftTweaker/issues/1739) issue, but theirs was a mod incompatibility from a different mod pack.

### The latest.log file

https://gist.github.com/RamenG0D/04a1c0629fdae2fbb9c77b6952df4899

**Comment by jaredlll08** [comment] 2024-07-06 10:00
Duplicate of https://github.com/CraftTweaker/CraftTweaker/issues/1742

**Closed as not planned by jaredlll08** 2024-07-06 10:00 UTC
