### ISSUE TITLE
[1.21] [Neoforge] Game crash on launch when CT installed

### ISSUE THREAD

**Issue by ffuentesm** [CraftTweaker/CraftTweaker#1747] opened 2024-06-25 14:37 UTC
### Issue description

![image](https://github.com/CraftTweaker/CraftTweaker/assets/44974827/f394804f-8db2-4a62-be5f-d5d863a609f5)
Game crash on launch 
When I launch the game, this error shows up. 

### Steps to reproduce

Launch the game with CT installed

### Script used

nan

### The crafttweaker.log file

nan

### Minecraft version

1.21

### Modloader

NeoForge

### Modloader version

21.0.36

### CraftTweaker version

20.0.11

### The latest.log file

https://pastebin.com/0DFGCg6L

**Comment by MokahTGS** [comment] 2024-06-25 21:32
Also seeing this.

Crashlog: https://pastebin.com/mALdDxd6

**Comment by jaredlll08** [comment] 2024-06-26 07:43
This was caused by NeoForge updating and making a breaking change, I just pushed a fix that should fix it.

**Closed as completed** 2024-06-26 07:43 UTC
