### ISSUE TITLE
java.io,EoFException, fieldsize is too long!

### ISSUE THREAD

**Issue by QianMuu** [CraftTweaker/CraftTweaker#1735] opened 2024-05-28 17:26 UTC
### Issue description

I'm using "CraftTweaker-forge-1.19.2-10.1.55"
When I added it to "mods", both the server and client started fine.
But if you want to connect to the server, it will display like this:
![qeqe](https://github.com/CraftTweaker/CraftTweaker/assets/50398180/959ad3c5-29ee-4541-9827-18ac2df506f7)
(Maybe it's a computer problem, because this doesn't happen on my other computer.)

This is the server log：
[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/15482842/latest.log)
[2024-05-29-1.log.gz](https://github.com/CraftTweaker/CraftTweaker/files/15484243/2024-05-29-1.log.gz)

This is the client log：
[debug.log](https://github.com/CraftTweaker/CraftTweaker/files/15485998/debug.log)
[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/15486002/latest.log)

### Steps to reproduce

Client cannot connect to server

### Script used

No script added

### The crafttweaker.log file

https://gist.github.com/QianMuu/ef4c52c107e2dd8f40d322f66ab9c8b5

### Minecraft version

1.19

### Modloader

Forge

### Modloader version

forge-43.3.13

### CraftTweaker version

CraftTweaker-forge-1.19.2-10.1.55

### Other relevant information

I added the "Cobblemon-forge-1.3.2+1.19.2" module, 
(maybe the two are incompatible?)

### The latest.log file

https://gist.github.com/QianMuu/3ef3b5bfd2d4788deb29aef67f3ddfa9

**Comment by jaredlll08** [comment] 2024-05-29 02:56
Please provide the latest.log file from the server

**Comment by QianMuu** [comment] 2024-05-29 10:19
> Please provide the latest.log file from the server请从服务器提供最新的. log文件

[debug.log](https://
[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/15482824/latest.log)
github.com/CraftTweaker/CraftTweaker/files/15482820/debug.log)

**Comment by QianMuu** [comment] 2024-05-29 10:20
> Please provide the latest.log file from the server请从服务器提供最新的. log文件

[debug.log](https://github.com/CraftTweaker/CraftTweaker/files/15482833/debug.log)
-
[latest.log](https://github.com/CraftTweaker/CraftTweaker/files/15482834/latest.log)

**Comment by QianMuu** [comment] 2024-05-29 10:39
> Please provide the latest.log file from the server

I have uploaded the server's "debug.log" and "latest.log".
Please take a look.

**Comment by jaredlll08** [comment] 2024-05-29 13:13
Sorry, I got confused, can you upload the client's latest.log file, I thought that was the one you had provided.

**Comment by QianMuu** [comment] 2024-05-29 14:41
> Sorry, I got confused, can you upload the client's latest.log file, I thought that was the one you had provided.

I have changed and uploaded the latest log of the client.

![0aa0e128-8be7-465d-ad83-5188c770e412](https://github.com/CraftTweaker/CraftTweaker/assets/50398180/ba78420b-8e94-4df6-aa78-52c1351a3115)
(This is the latest error message)

**Comment by jaredlll08** [comment] 2024-05-29 14:54
Okay, both logs have nothing in them, no mention of any error, so I don't know where I would even start looking to fix this.

I am unable to reproduce, and as you say, it works on another computer, so unfortunately I am going to close this as being something related to your computer specifically.
I do see that you are using Java 18 in the client log, but the server is using Java 17, it is possible that this could cause it.

I also see that you are playing in offline mode, which could potentially cause issues.

**Closed as not planned by jaredlll08** 2024-05-29 14:54 UTC
