### ISSUE TITLE
Unable to use the onBlockHarvestDrops event

### ISSUE THREAD

**Issue by belathus** [CraftTweaker/CraftTweaker#654] opened 2018-10-20 21:09 UTC
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unnofficial version of Minetweaker or Crafttweaker please report it to the person who gave you the version. Also please look at the other issues to make sure that you are not creating a duplicate.

#### What happens:
Every time a block is broken, an error is reported to the client and to the crafttweaker.log file. The action (```print("test");```) is not printed.

#### What you expected to happen:
"Test" to be printed to the log file every time one breaks a block.
The commented out code should increase the amount of drops depending on the fortune level, but it is commented out and should do nothing.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
https://github.com/belathus/Wanderlust-Renewed/blob/d33/scripts/drops_on_harvest.zs

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
This is the error that pops up: https://gist.github.com/belathus/bf91b4f76b1b76cf38e4e67ca2c0cb4b
Here is the log, but even Gist refuses to do the entire log (it is 39000 lines long): https://gist.github.com/belathus/7653d15a9fd1d9c1c30bc212519d65b8
Here is the log with 30,000 salis mundis recipes removed: https://gist.github.com/belathus/3fba4ae12d048f5ebc836687d95f1928

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Crafttweaker: 4.1.11
- Using a server: No

#### Your most recent log file where the issue was present: 
https://gist.github.com/belathus/1d3747928ce0c7864fb4785e8f3da739

**Comment by kindlich** [comment] 2018-10-26 05:43
This is most likely caused by an unforeseen loader conflict in which two loaders use the same class name. 

This will be fixed, for now try to see if it works without Contenttweaker so I can validate that it's coming from that issue?

**Comment by kindlich** [comment] 2019-01-04 17:26
Any further info on this or can this be closed?

**Comment by jaredlll08** [comment] 2019-06-09 16:04
I tested this myself and can't reproduce.

**Closed as completed by jaredlll08** 2019-06-09 16:04 UTC
