### ISSUE TITLE
ß inside comments leads to an error

### ISSUE THREAD

**Issue by Wxrlds** [CraftTweaker/CraftTweaker#1188] opened 2021-02-28 18:05 UTC
#### Issue Description:  
Putting the german "ß" into a comment, no matter if inside ``/* */`` or behind ``//`` leads to an error when reloading

#### What happens:  
Script errors

#### What you expected to happen:  
Script shouldn't error

#### Scripts used:  
1. Script: ``//ß``
2. Script: ``/* ß */``

#### crafttweaker.log file:  
Lines between 7039-7179 show the error if the first script is used and everything after 7179 shows error of the second script
https://gist.github.com/Wxrlds/f836a33fea206ce7d9e1ee15f34fb895

____
#### Environment:  

- Minecraft Version: 1.16.5
- Forge Version: 36.0.43
- CraftTweaker Version: CraftTweaker-1.16.5-7.1.0.135
- Are you using a server: No, Singleplayer

#### Game log:  
https://gist.github.com/Wxrlds/ede7d0946a005837e3235120e2ab1ff8

**Comment by jaredlll08** [comment] 2021-02-28 18:26
Duplicate of https://github.com/CraftTweaker/CraftTweaker/issues/1095

**Closed as completed by jaredlll08** 2021-02-28 18:26 UTC
