### ISSUE TITLE
Getting an error with the code but cant figure out what is the issue.

### ISSUE THREAD

**Issue by Jennifercutixx** [CraftTweaker/CraftTweaker#1027] opened 2020-08-01 14:17 UTC
Ive added tons before and when i tried it out and finihsed the recipes. It gives me an error on code to large and dunno if its bc added too many or something. Please help

![Untitled](https://user-images.githubusercontent.com/60190810/89103459-ff39e580-d409-11ea-83e8-ee8cda2c7d73.png)

and yes i have renamed it before and worked completly fine. Any help on this would be good thank you.

**Comment by Jennifercutixx** [comment] 2020-08-01 14:46
It seems that i was corrected and the script couldnt load more then a certin amount of recipe lines. But i hope the mod will in the future be able to handle more recipes in the future. but still i love the mod for allowing ppl who ant good at java script to add recipes into the game. ^^

**Comment by kindlich** [comment] 2020-08-01 14:53
Split your script into multiple files.

**Comment by Jennifercutixx** [comment] 2020-08-01 15:00
ye that might work unless you know it works. Thank you for the tip never would have thought of that tbh haha

**Comment by kindlich** [comment] 2020-08-01 15:11
The problem is that ZS will put everything you write in your script into one method.
Java has a hard set limit on how many instructions can be inside of one method.

So using multiple script files solves that problem since each script file will be in its own method.

**Comment by Jennifercutixx** [comment] 2020-08-01 15:25
aww okies thank you very much ^^

**Closed as completed** 2020-08-01 15:41 UTC
