### ISSUE TITLE
CraftTweaker (crafttweaker) has failed to load correctly

### ISSUE THREAD

**Issue by SevenChords** [CraftTweaker/CraftTweaker#1542] opened 2022-08-01 18:29 UTC
### Issue description

Getting the Error from the title when trying to launch any 1.18 modpack that uses crafttweaker (crafttweaker version 9.1.182 installed, tried some older version, getting the same on any version i've tested)

### Script used

any that i tested (any that were included with any of the tested modpacks)

### The crafttweaker.log file

can't access ct log, here is the crash report: https://pastebin.pl/view/598d15d6

### Minecraft version

1.18

### Modloader

Forge

### Modloader version

40.1.68

### CraftTweaker version

9.1.182

### Other relevant information

possibly OS related, macOS 12.5, using ATLauncher version 3.4.19.3, happens both with my system java and with the option "use java shipped by the game" enabled.

### The latest.log file

https://pastebin.pl/view/507a8378

**Comment by jaredlll08** [comment] 2022-08-01 19:32
duplicate of:
https://github.com/CraftTweaker/CraftTweaker/issues/1434
https://github.com/CraftTweaker/CraftTweaker/issues/899

and probably a few more that I've forgotten, the actual issue is caused by ATLauncher and there is more information about it here:
https://github.com/ATLauncher/ATLauncher/issues/502

**Closed as not planned by jaredlll08** 2022-08-01 19:32 UTC
