### ISSUE TITLE
[1.12.2]Game freezed while loading at Finishing up stage.

### ISSUE THREAD

**Issue by esv110842** [CraftTweaker/CraftTweaker#890] opened 2019-12-06 16:51 UTC
#### Issue Description:
Trying to add 50+ mods to my minecraft that already had 200+ mods,including JustEnoughIDs to fix the problem of excessed ids.

#### What happens:
Application became Not Responding when forge loading to Finishing up stage,said Crafttweaker2 was LoadComplete and game became freezed.

#### What you expected to happen:
Game loaded successful and worked properly.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):
[https://pastebin.com/kBuipmVW](url)
[https://pastebin.com/6nzjL4Z1](url)
[https://pastebin.com/wqmcX36h](url)
[https://pastebin.com/p8Y14RZ7)](url)

#### crafttweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):
[https://pastebin.com/JWhxMHCw](url)

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft:1.12.2
- Forge:14.23.5.2847
- Crafttweaker:1.12-4.1.19 
- Using a server:No 
- If yes, does the client have the exact same scripts?

#### Your most recent log file where the issue was present: 

latest[https://gist.github.com/esv110842/3de6ee604abba872b2e40b2bca48b1e8](url)
debug[https://gist.github.com/esv110842/3bd5677820d3575ac45682601cf0186a](url)

#### Additional Information
Mod list
[https://pastebin.com/uBdAqrDB](url)

:

**Comment by jaredlll08** [comment] 2019-12-06 16:52
Duplicate of https://github.com/CraftTweaker/CraftTweaker/issues/885

The more mods you have, the worse it gets unfortunately.

**Closed as completed by jaredlll08** 2019-12-06 16:52 UTC

**Comment by jaredlll08** [comment] 2019-12-07 16:27
related to:
https://github.com/CraftTweaker/CraftTweaker/issues/829
adding `#disable_search_tree` to your script may fix the issue.
