### ISSUE TITLE
Some commands should be available without permissions

### ISSUE THREAD

**Issue by Shahelion** [CraftTweaker/CraftTweaker#391] opened 2017-11-29 08:29 UTC
#### Issue Description:
The command to identify the held item cannot be used if cheats are disabled. No reason for this, honestly. Same with the help command (and because of this, possibly others that I don't know of).

#### What happens:
Prints in chat "You do not have permission to use this command"

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 14.23.1.2555
- Crafttweaker: 4.1.10

**Comment by kindlich** [comment] 2017-11-29 13:12
The craftTweaker commands are only needed for pack makers and operators.
Giving normal users access to them could possibly break some modpacks, since `/ct hand` would also return all stored nbt-data!

Also, the logging features might be abused if people were able to publicly access them

**Comment by Shahelion** [comment] 2017-11-29 19:22
I honestly don't see how the hand command could cause problems.

Logging features?

**Comment by bookerthegeek** [comment] 2017-11-29 20:17
@kindlich

Would it possible to get of list of all the permission nodes used by this mod though please so that we can let specific people use some of the commands? On our network we have staff who do not have creative access who fix pack recipes or such not due to bugs / Glitches / Banned Items (Banned for server stability) and it would be nice to not have to either give them creative access or grab one of the few Admins that do have creative access to get the names of items.

The ability to set the permission level for either specific commands or all commands would be a time saver for us. If not I understand but most well managed servers should know how to properly prohibit permissions so normal players can not break things, and if not they will learn quickly. lol

**Comment by Shahelion** [comment] 2017-11-30 20:08
OK, so this is strange...even after enabling cheats for a singleplayer world, I am still unable to use those commands. Not sure what's going on there.

**Comment by jaredlll08** [comment] 2017-11-30 20:12
what error does it give?

**Comment by Shahelion** [comment] 2017-11-30 20:44
It simply says I do not have permission, but i dont know how i could have any more.

**Comment by jaredlll08** [comment] 2017-11-30 20:49
can you use any non forge / mc OP command?

**Comment by Shahelion** [comment] 2017-11-30 21:10
Ok so that particular problem is fixed. Initial issue still stands.

**Comment by kindlich** [comment] 2017-11-30 21:19
@bookerthegeek Sorry, but I have no clue about permission nodes...
CT is open source however, you can always just do a PR if you want a feature to be added lol

What I can tell you is that all commands require a permission level of 4
That could be changeable though, maybe OP-Level 1?

**Comment by bookerthegeek** [comment] 2017-11-30 23:57
@kindlich let me reach out to some of our other server staff and see if I can't get you the information. But yes, setting it to something other than OP would be nice. I know that Song Forge replaces Vanilla OP (not your problem I know) but I don't know off the top of my head what they do use.

**Comment by jaredlll08** [comment] 2018-01-10 01:51
I'm closing this, the problem is that there may be some packs with "hidden" items or something of the like, where the actual item shouldn't be known to the player, and there is the problem of lag spam, which can get big and cause issues

**Closed as completed by jaredlll08** 2018-01-10 01:51 UTC

**Comment by Shahelion** [comment] 2018-01-10 04:14
Now, I have no idea if this is possible or not, but what about a config option to allow the commands to be used by non-OP players? Server-side config, of course.

Or does it just not work that way?

**Comment by jaredlll08** [comment] 2018-01-10 09:35
Doesn't work that way.
