### ISSUE TITLE
Using single add tag function with multiple objects gives error.

### ISSUE THREAD

**Issue by RHSD** [CraftTweaker/CraftTweaker#1196] opened 2021-03-08 11:06 UTC
#### Intro:  
Using single add tag function with multiple objects gives error.

#### Issue Description:  
If you add multiple objects to a single line of tag.add() it gives an error; for example `tagx.add(<block:minecraft:dirt>);` works but the script used below does not.

#### What happens:  
1 parameters expected but 57 given. Script is invalid.

#### What you expected to happen:  
Expected it to accept all objects.

#### Script used:  
`always_breakable.add(<block:minecraft:snow>, <block:extcaves:mushroom_sweetshroom>, <block:extcaves:mushroom_goldishroom>, <block:extcaves:mushroom_shinyshroom>, <block:extcaves:mushroom_lumishroom>, <block:extcaves:mushroom_fluoshroom>, <block:extcaves:mushroom_rockshroom>, <block:extcaves:moss_dry>, <block:extcaves:moss_fire>, <block:extcaves:moss_frozen>, <block:extcaves:moss_hanging_roots>, <block:extcaves:moss_humid_ground>, <block:extcaves:cave_vine_end>, <block:extcaves:rock_flint>, <block:extcaves:rock_pebble_stone>, <block:extcaves:rock_pebble_andesite>, <block:extcaves:rock_pebble_diorite>, <block:extcaves:rock_pebble_granite>, <block:extcaves:rock_pebble_sedimentstone>, <block:extcaves:rock_pebble_lavastone>, <block:extcaves:rockpile_two_stone>, <block:extcaves:rockpile_two_sedimentstone>, <block:extcaves:rockpile_two_lavastone>, <block:extcaves:rockpile_two_andesite>, <block:extcaves:rockpile_two_diorite>, <block:extcaves:rockpile_two_granite>, <block:extcaves:rockpile_three_stone>, <block:extcaves:rockpile_three_sedimentstone>, <block:extcaves:rockpile_three_lavastone>, <block:extcaves:rockpile_three_andesite>, <block:extcaves:rockpile_three_diorite>, <block:extcaves:rockpile_three_granite>, <block:extcaves:treasure_pot>, <block:extcaves:treasure_pot_short>, <block:extcaves:treasure_pot_long>, <block:extcaves:treasure_pot_quartz_short>, <block:extcaves:treasure_pot_quartz_long>, <block:extcaves:decoration_pot>, <block:extcaves:decoration_pot_short>, <block:extcaves:decoration_pot_long>, <block:extcaves:decoration_pot_quartz_short>, <block:extcaves:decoration_pot_quartz_long>, <block:projectvibrantjourneys:twigs>, <block:projectvibrantjourneys:fallen_leaves>, <block:projectvibrantjourneys:rocks>, <block:projectvibrantjourneys:mossy_rocks>, <block:projectvibrantjourneys:sandstone_rocks>, <block:projectvibrantjourneys:red_sandstone_rocks>, <block:projectvibrantjourneys:ice_chunks>, <block:projectvibrantjourneys:bones>, <block:projectvibrantjourneys:charred_bones>, <block:projectvibrantjourneys:bones>, <block:projectvibrantjourneys:pinecones>, <block:projectvibrantjourneys:seashells>, <block:projectvibrantjourneys:sea_oats>, <block:projectvibrantjourneys:cattail>, <block:projectvibrantjourneys:bark_mushroom>);
`

#### crafttweaker.log file:  
https://pastebin.com/djFx0xgM

____
#### Environment:  
- Minecraft Version: 1.16.5
- Forge Version: 36.0.45
- CraftTweaker Version: 7.1.0.141
- Are you using a server: No
- If yes, does the client have the exact same scripts?

**Comment by jaredlll08** [comment] 2021-04-24 02:40
unable to reproduce, so I'm guessing this got fixed in the past 100 releases.

If this is still an issue, please re-open / make a new issue

**Closed as completed by jaredlll08** 2021-04-24 02:40 UTC

**Comment by Terra-B-Welch** [comment] 2025-06-05 01:52
I know odds of any response are zero but whatever...

I'm more or less wondering how you even got block tags working in 1.16.5 Every time I try to add block tags to blocks I'm met with an error saying "Could not find tag manager with folder 'block'. Make sure it exists!"

**Comment by jaredlll08** [comment] 2025-06-05 01:55
Iirc the block tag bracket in 1.16.5 is `blocks`, use `/ct hand` while holding sand or dirt for example, it should print it

**Comment by Terra-B-Welch** [comment] 2025-06-05 02:05
Yes I've done that, also surprised at even getting a response.

If you're wondering what the script is, it's this. https://pastebin.com/Q4mqmBQb

I'm trying to allow crops to grow during certain seasons in serene seasons by adding the block tags.

**Comment by jaredlll08** [comment] 2025-06-05 02:07
Screenshot the output of `/ct hand` while holding sand and send the screenshot here please

**Comment by Terra-B-Welch** [comment] 2025-06-05 12:20
![Image](https://github.com/user-attachments/assets/a1900054-bd87-4a84-a691-2f3b205bf23f)

the full output here, since it doesn't all fit in the image.
https://pastebin.com/x1UD2VqW

**Comment by jaredlll08** [comment] 2025-06-05 16:08
> `<tag:blocks:forge:sand>`

I was right, you need to be using `<tag:blocks` instead of `<tag:block`.

Your full script should be:
```zenscript
import crafttweaker.api.tag.MCTag;
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.item.MCItemDefinition;
import stdlib.List;

<tag:blocks:sereneseasons:spring_crops>.add(<block:pamhc2crops:pamwintersquashcrop>);
<tag:blocks:sereneseasons:spring_crops>.add(<block:farmersdelight:cabbages>);
<tag:blocks:sereneseasons:spring_crops>.add(<block:pamhc2crops:pamricecrop>);
<tag:blocks:sereneseasons:spring_crops>.add(<block:blue_skies:winter_leaves>);
<tag:blocks:sereneseasons:spring_crops>.add(<block:blue_skies:fiery_beans>);
<tag:blocks:sereneseasons:spring_crops>.add(<block:blue_skies:scalefruits>);
<tag:blocks:sereneseasons:spring_crops>.add(<block:blue_skies:pine_fruits>);

<tag:blocks:sereneseasons:summer_crops>.add(<block:pamhc2crops:pamgarliccrop>);
<tag:blocks:sereneseasons:summer_crops>.add(<block:blue_skies:winter_leaves>);
<tag:blocks:sereneseasons:summer_crops>.add(<block:blue_skies:fiery_beans>);
<tag:blocks:sereneseasons:summer_crops>.add(<block:blue_skies:scalefruits>);
<tag:blocks:sereneseasons:summer_crops>.add(<block:blue_skies:pine_fruits>);

<tag:blocks:sereneseasons:autumn_crops>.add(<block:pamhc2crops:pamricecrop>);
<tag:blocks:sereneseasons:autumn_crops>.add(<block:pamhc2crops:pamcabbagecrop>);
<tag:blocks:sereneseasons:autumn_crops>.add(<block:blue_skies:winter_leaves>);
<tag:blocks:sereneseasons:autumn_crops>.add(<block:blue_skies:fiery_beans>);
<tag:blocks:sereneseasons:autumn_crops>.add(<block:blue_skies:scalefruits>);
<tag:blocks:sereneseasons:autumn_crops>.add(<block:blue_skies:pine_fruits>);

<tag:blocks:sereneseasons:winter_crops>.add(<block:pamhc2crops:pamwintersquashcrop>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:pamhc2crops:pamcabbagecrop>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:pamhc2crops:pamtomatillocrop>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:pamhc2crops:pamoatscrop>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:pamhc2crops:pamrhubarbcrop>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:blue_skies:winter_leaves>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:blue_skies:fiery_beans>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:blue_skies:scalefruits>);
<tag:blocks:sereneseasons:winter_crops>.add(<block:blue_skies:pine_fruits>);
```

**Comment by Terra-B-Welch** [comment] 2025-06-05 16:40
welp, here I go failing to notice the small things again, thanks >.<

That's what I get for trying to tamper with code in the middle of the night shortly before bedtime, I miss something small like that.
