### ISSUE TITLE
Biomes O' Plenty flax to string recipe not created

### ISSUE THREAD

**Issue by WrongWeekend** [CraftTweaker/CraftTweaker#433] opened 2018-01-27 20:01 UTC
#### Intro:
I'm attempting to create a script that allows the shapeless crafting of two flax from Biomes O' Plenty into one vanilla Minecraft string.

#### Issue Description:

Upon starting a game with the script, the errors appear in chat:

```
ERROR: newrecipes.zs:1: Could not resolve <biomesoplenty : flax>
ERROR: newrecipes.zs:1: Could not resolve <biomesoplenty : flax>
ERROR: Null not allowed in shapeless recipes! Recipe for: <minecraft:string> not created!

```
As far as I know there are no nulls used in the script. There are also no spaces around the colons in the script itself, although the error says otherwise.

#### What happens:

The above mentioned errors are displayed in chat and the recipe is not added or functional.

#### What you expected to happen:

The recipe would be added and functional.

#### Script used (Please Pastebin or gist your script, posting an unpasted or ungist'd script will automatically close this issue):

https://pastebin.com/JwcSYWCH

#### Minetweaker.log file (Please Pastebin or gist your file, posting an unpasted or ungist'd file will automatically close this issue):

https://pastebin.com/M7Rmwp3i
____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.1.2581
- Crafttweaker: 4.1.0

#### Your most recent log file where the issue was present: 

https://pastebin.com/g6ZwBE9a

**Comment by kindlich** [comment] 2018-01-27 21:44
Hold the flax item in your hand and do `/ct hand`
The issue is that CrT cannot resolve `<biomesoplenty : flax>` so it cannot craete the recipe for you.
Resolving means taking what is inside the `<>` and turning it into an ItemStack that MC knows how to handle.

If you use that command, the correct name should be vopied to your clipboard and you can simply paste it into your script

**Comment by jaredlll08** [comment] 2018-02-02 14:33
Since the author never replied I tested it myself...

![image](https://user-images.githubusercontent.com/5553605/35738193-c2d424f8-0836-11e8-80c3-c8b8a5af1adb.png)

**Closed as completed by jaredlll08** 2018-02-02 14:33 UTC
